CRISIS_PHRASES = [
    "i hate myself", "i hate my life", "i hate everything",
    "i hate being alive", "i hate living", "i hate existing",
    "i hate this", "i hate me", "i hate who i am", "i hate my body",
    "i hate my mind", "i hate my brain", "i hate my thoughts",
    "i hate my existence", "i hate being me", "i hate myself so much",
    "i hate my stupid life", "i hate this life", "i hate this world",
    "i hate everyone", "i hate people", "i hate everything about me",
    "i hate everything about my life", "i hate waking up",
    "i hate waking up in the morning", "i hate mornings",
    "i hate being awake", "i hate being conscious", "i hate being here",
    "i hate that i'm alive", "i hate that i exist",
    "i hate that i was born", "i hate being born",
    "i wish i was never born", "i wish i was dead", "i wish i were dead",
    "i wish i could die", "i wish i could disappear", "i wish i could just die",
    "i wish i could kill myself", "i wish i could end it",
    "i wish i could end it all", "i wish i could end my life",
    "i wish i could stop existing", "i wish i could just disappear",
    "i wish i could vanish", "i wish i could go to sleep and never wake up",
    "i wish i could fall asleep and never wake up",
    "i wish i never existed", "i wish i was never here",
    "i wish i wasn't born", "i wish i wasn't here",
    "i wish i wasn't alive", "i wish i wasn't living",
    "i wish i wasn't real", "i wish i was invisible",
    "i wish i was gone", "i wish i was elsewhere",
    "i wish i was dead already", "i wish i was dead right now",
    "i wish i was dead and gone", "i wish i was dead and buried",
    "i wish i was in a better place", "i wish i was anywhere but here",
    "i wish i could escape", "i wish i could run away",
    "i wish i could leave", "i wish i could go away",
    "i wish i could go somewhere else", "i wish i could get away",
    "i wish i could get out of here", "i wish i could get out of this life",
    "i wish i could get out of this world", "i wish i could get out of my head",
    "i wish i could get out of my body", "i wish i could get out of my mind",
    "i wish i could get out of my own head", "i wish i could escape my mind",
    "i wish i could escape my thoughts", "i wish i could escape my life",
    "i wish i could escape this world", "i wish i could escape reality",
    "i wish i could escape everything", "i wish i could just escape",
    "i wish i could just run away", "i wish i could just leave",
    "i wish i could just disappear", "i wish i could just vanish",
    "i wish i could just stop existing", "i wish i could just not exist",
    "i wish i could just be gone", "i wish i could just be dead",
    "i wish i could just die", "i wish i could just kill myself",
    "i wish i could just end it", "i wish i could just end it all",
    "i wish i could just end my life", "i wish i could just end everything",
    "i wish i could just stop living", "i wish i could just stop being alive",
    "i wish i could just stop existing", "i wish i could just stop breathing",
    "i wish i could just stop my heart", "i wish i could just stop thinking",
    "i wish i could just stop feeling", "i wish i could just stop hurting",
    "i wish i could just stop suffering", "i wish i could just stop the pain",
    "i wish i could just make it stop", "i wish i could just make the pain stop",
    "i wish i could just make it all stop", "i wish i could just make everything stop",
    "i wish i could just make the thoughts stop", "i wish i could just make the voices stop",
    "i wish i could just make the noise stop", "i wish i could just make it all go away",
    "i wish i could just make everything go away", "i wish i could just make the pain go away",
    "i wish i could just make the hurt go away", "i wish i could just make the sadness go away",
    "i wish i could just make the depression go away", "i wish i could just make the anxiety go away",
    "i wish i could just make the emptiness go away", "i wish i could just make the loneliness go away",
    "i wish i could just make the numbness go away", "i wish i could just feel something",
    "i wish i could just feel anything", "i wish i could just feel normal",
    "i wish i could just feel okay", "i wish i could just feel better",
    "i wish i could just feel happy", "i wish i could just feel love",
    "i wish i could just feel loved", "i wish i could just feel wanted",
    "i wish i could just feel needed", "i wish i could just feel human",
    "i wish i could just be normal", "i wish i could just be okay",
    "i wish i could just be happy", "i wish i could just be at peace",
    "i wish i could just be free", "i wish i could just be done",
    "i wish i could just be over", "i wish i could just be finished",
    "i wish i could just be done with life", "i wish i could just be done with everything",
    "i wish i could just be done with this", "i wish i could just be done with it all",
    "i wish i could just give up", "i wish i could just let go",
    "i wish i could just stop", "i wish i could just quit",
    "i wish i could just surrender", "i wish i could just give in",
    "i wish i could just stop trying", "i wish i could just stop fighting",
    "i wish i could just stop caring", "i wish i could just cease to exist",
    "i wish i could just cease to be", "i wish i could just fade away",
    "i wish i could just disappear into nothing", "i wish i could just dissolve",
    "i wish i could just melt away", "i wish i could just evaporate",
    "i wish i could just be erased", "i wish i could just be deleted",
    "i wish i could just be removed", "i wish i could just be forgotten",
    "i wish i could just be left alone", "i wish i could just be alone",
    "i wish i could just be by myself", "i wish i could just be somewhere else",
    "i wish i could just be anywhere but here", "i wish i could just be anywhere else",
    "i wish i could just be gone from here", "i wish i could just leave this place",
    "i wish i could just leave this world", "i wish i could just leave this life",
    "i wish i could just leave everything", "i wish i could just leave everyone",
    "i wish i could just leave it all behind", "i wish i could just leave this behind",
    "i wish i could just leave my life behind", "i wish i could just leave my problems behind",
    "i wish i could just leave my pain behind", "i wish i could just leave my suffering behind",
    "i wish i could just leave my sadness behind", "i wish i could just leave my depression behind",
    "i wish i could just leave my anxiety behind", "i wish i could just leave my thoughts behind",
    "i wish i could just leave my mind behind", "i wish i could just leave my body behind",
    "i wish i could just leave my self behind", "i wish i could just leave myself behind",
    "i wish i could just leave who i am behind", "i wish i could just leave my identity behind",
    "i wish i could just leave my past behind", "i wish i could just leave my memories behind",
    "i wish i could just leave my trauma behind", "i wish i could just leave my hurt behind",
    "i wish i could just leave my scars behind", "i wish i could just leave my wounds behind",
    "i wish i could just leave my brokenness behind", "i wish i could just leave my broken self behind",
    "i wish i could just leave my broken life behind", "i wish i could just leave my broken mind behind",
    "i wish i could just leave my broken heart behind", "i wish i could just leave my broken soul behind",
    "i wish i could just leave my broken spirit behind", "i wish i could just leave my broken body behind",
    "i wish i could just leave this broken world behind", "i wish i could just leave this broken life behind",
    "i wish i could just leave this broken body behind", "i wish i could just leave this broken mind behind",
    "i wish i could just leave this broken heart behind", "i wish i could just leave this broken soul behind",
    "i wish i could just leave this broken spirit behind", "i wish i could just leave this broken self behind",
    "i wish i could just leave this broken existence behind", "i wish i could just leave this broken reality behind",
    "i wish i could just escape this broken world", "i wish i could just escape this broken life",
    "i wish i could just escape this broken existence", "i wish i could just escape this broken reality",
    "i wish i could just escape this broken self", "i wish i could just escape this broken mind",
    "i wish i could just escape this broken body", "i wish i could just escape this broken heart",
    "i wish i could just escape this broken soul", "i wish i could just escape this broken spirit",
    "i wish i could just escape my broken self", "i wish i could just escape my broken mind",
    "i wish i could just escape my broken body", "i wish i could just escape my broken heart",
    "i wish i could just escape my broken soul", "i wish i could just escape my broken spirit",
    "i wish i could just escape my broken life", "i wish i could just escape my broken existence",
    "i wish i could just escape my broken reality", "i wish i could just escape my broken world",
    "i wish i could just escape my broken home", "i wish i could just escape my broken family",
    "i wish i could just escape my broken relationships", "i wish i could just escape my brokenness",
    "i wish i could just escape the pain", "i wish i could just escape the hurt",
    "i wish i could just escape the suffering", "i wish i could just escape the sadness",
    "i wish i could just escape the depression", "i wish i could just escape the anxiety",
    "i wish i could just escape the emptiness", "i wish i could just escape the loneliness",
    "i wish i could just escape the numbness", "i wish i could just escape the darkness",
    "i wish i could just escape the void", "i wish i could just escape the abyss",
    "i wish i could just escape the nothingness", "i wish i could just escape the chaos",
    "i wish i could just escape the noise", "i wish i could just escape the thoughts",
    "i wish i could just escape the voices", "i wish i could just escape the memories",
    "i wish i could just escape the flashbacks", "i wish i could just escape the nightmares",
    "i wish i could just escape the dreams", "i wish i could just escape the reality",
    "i wish i could just escape the world", "i wish i could just escape the universe",
    "i wish i could just escape existence", "i wish i could just escape life",
    "i wish i could just escape death", "i wish i could just escape everything",
    "i wish i could just escape it all", "i wish i could just escape this",
    "i wish i could just escape that", "i wish i could just escape from here",
    "i wish i could just escape from this", "i wish i could just escape from everything",
    "i wish i could just escape from it all", "i wish i could just escape from this life",
    "i wish i could just escape from this world", "i wish i could just escape from this reality",
    "i wish i could just escape from this existence", "i wish i could just escape from this body",
    "i wish i could just escape from this mind", "i wish i could just escape from this pain",
    "i wish i could just escape from this suffering", "i wish i could just escape from this sadness",
    "i wish i could just escape from this depression", "i wish i could just escape from this anxiety",
    "i wish i could just escape from this emptiness", "i wish i could just escape from this loneliness",
    "i wish i could just escape from this numbness", "i wish i could just escape from this darkness",
    "i wish i could just escape from this void", "i wish i could just escape from this abyss",
    "i wish i could just escape from this nothingness", "i wish i could just escape from this chaos",
    "i wish i could just escape from this noise", "i wish i could just escape from these thoughts",
    "i wish i could just escape from these voices", "i wish i could just escape from these memories",
    "i wish i could just escape from these flashbacks", "i wish i could just escape from these nightmares",
    "i wish i could just escape from these dreams", "i wish i could just escape from this universe",
    "i wish i could just get away from here", "i wish i could just get away from this",
    "i wish i could just get away from everything", "i wish i could just get away from it all",
    "i wish i could just get away from this life", "i wish i could just get away from this world",
    "i wish i could just get away from this reality"
]