CRISIS_PHRASES = [
    # --- Direct suicidal ideation ---
    "i want to die",
    "i wanna die",
    "i want to kill myself",
    "i wanna kill myself",
    "i'm going to kill myself",
    "i am going to kill myself",
    "i will kill myself",
    "i'm gonna kill myself",
    "i am gonna kill myself",
    "kill myself",
    "kms",
    "i want to end my life",
    "i'm going to end my life",
    "i will end my life",
    "end my life",
    "i want to commit suicide",
    "commit suicide",
    "i'm suicidal",
    "i am suicidal",
    "suicidal thoughts",
    "i'm thinking about suicide",
    "i am thinking about suicide",

    # --- Passive suicidal ideation ---
    "i wish i was dead",
    "i wish i were dead",
    "i wish i could die",
    "i wish i could just die",
    "i wish i was never born",
    "i wish i wasn't born",
    "i wish i could go to sleep and never wake up",
    "i wish i could fall asleep and never wake up",
    "i don't want to be alive",
    "i don't want to live anymore",
    "i don't want to exist",
    "i want to disappear",
    "i want to cease to exist",
    "i want to not wake up",
    "i wish i could disappear",
    "i wish i could stop existing",

    # --- Self-harm intent or urges ---
    "i want to cut myself",
    "i want to hurt myself",
    "i want to self harm",
    "i want to self-harm",
    "i'm going to cut myself",
    "i cut myself",
    "i self harm",
    "cutting myself",
    "i want to burn myself",
    "i want to injure myself",
    "i want to harm myself",
    "self harm",
    "self-harm",

    # --- Hopelessness / no future ---
    "there is no hope",
    "there's no hope",
    "i have no hope",
    "nothing will ever get better",
    "things will never get better",
    "it will never get better",
    "i see no future",
    "there is no point in living",
    "there's no point in living",
    "no reason to live",
    "i have no reason to live",
    "life is pointless",
    "i have nothing to live for",

    # --- Feeling trapped / no way out ---
    "i feel trapped",
    "there is no way out",
    "there's no way out",
    "i can't escape this pain",
    "i can't take this anymore",
    "i can't go on",
    "i can't do this anymore",
    "i can't live like this",
    "i'm stuck in this pain",
    "i feel like there's no escape",
    "i feel like there is no way out",

    # --- Perceived burdensomeness ---
    "everyone would be better off without me",
    "they'd be better off without me",
    "i'm a burden to everyone",
    "i am a burden",
    "my family would be better off without me",
    "the world would be better without me",
    "i'm worthless to everyone",
    "no one needs me",
    "everyone is better off without me",

    # --- Giving up / inability to cope ---
    "i give up",
    "i'm done trying",
    "i can't cope anymore",
    "i've had enough",
    "i'm tired of fighting",
    "i don't want to fight anymore",
    "i've lost the will to live",
    "i've given up",
    "i'm done with life",
    "i can't handle this anymore",
    "i can't deal with this anymore",
    "i'm at the end of my rope",

    # --- Planning or preparatory actions ---
    "i bought a rope",
    "i have a plan to kill myself",
    "i wrote a suicide note",
    "i'm going to jump off",
    "i'm going to overdose",
    "i'm going to shoot myself",
    "i'm going to hang myself",
    "i'm going to slit my wrists",
    "i know how i'll do it",
    "i have the means to kill myself",
    "i've been saving pills",
    "i've written my note",

    # --- Finality / goodbye language ---
    "goodbye forever",
    "this is goodbye",
    "i'm saying goodbye",
    "i'm leaving now",
    "you'll be better off without me",
    "i won't be here much longer",
    "this is the end",
    "i'm ending it all",
    "i'm saying my final goodbye",

    # --- Extreme self-hatred / worthlessness ---
    "i hate myself",
    "i hate my life",
    "i hate being alive",
    "i hate existing",
    "i hate who i am",
    "i'm worthless",
    "i'm useless",
    "i'm a failure",
    "i hate everything about me",
    "i'm a waste of space",
    "i'm a complete failure",

    # --- Urges / commands to act ---
    "i need to kill myself",
    "i have to kill myself",
    "i must die",
    "i need to end it",
    "i have to end it all",
    "i need to disappear",
    "the voices tell me to kill myself",
    "i'm being told to kill myself",
    "i need to self destruct",
]